### ISSUE TITLE
Implement Day Templates

Just like how one might have a "leg day" at the gym, we want to user to be able to focus on certain exercises and hide the rest.

### ISSUE THREAD

**Issue by MNandor** [MNandor/wout#1]
Just like how one might have a "leg day" at the gym, we want to user to be able to focus on certain exercises and hide the rest.

MVP:
- able to add, remove, and modify day templates
- able to select day templates
- show/hide exercise types based on template

Additional features:
- automatically change template based on user-set schedule
- record template changes as logs

**Comment by BinaKaiser** [comment]
I can try to do this. Can you give some mockups of how you imagine the UI?

**Comment by BinaKaiser** [comment]
#2 looks good.

I'm assuming it's going to require a RecycleView? Can you explain that to me?

**Comment by MNandor** [comment]
RecyclerView is a ViewGroup in Android that is used to display a scrolling list of elements. It is a more advanced and flexible version of ListView, and is a key component in many Android apps.

RecyclerView provides several benefits over ListView, including the ability to efficiently display large datasets, the ability to reuse and recycle individual item views, and the ability to easily add and remove items from the list.

To use RecyclerView in your Android app, you will need to create a RecyclerView widget in your layout file and define an adapter to bind the data to the RecyclerView. The adapter is responsible for creating and binding individual views for each item in the dataset, and for handling user interactions with the items in the list.

RecyclerView also provides several built-in layout managers, such as LinearLayoutManager and GridLayoutManager, which can be used to control the layout and scrolling behavior of the list. You can also create custom layout managers to support more advanced or custom layout scenarios.

Overall, RecyclerView is a powerful and flexible tool for displaying scrolling lists of data in Android apps. It provides several benefits over ListView, and is a key component in many modern Android apps.

You can copy my existing RecyclerView with some modifications. DM me if you need any more help :)
